export const FALL_ITEM_TRANSITION_DURATION = 520;
export const FALL_ITEM_STAGGER_DELAY = 80;
export const WORK_ITEM_TRANSITION_DURATION = 720;
export const WORK_ITEM_STAGGER_DELAY = 100;

export const DEFAULT_FALL_EASE = "cubic-bezier(0.16, 1, 0.3, 1)";

export const FALL_TRANSITION = `transform ${FALL_ITEM_TRANSITION_DURATION}ms ${DEFAULT_FALL_EASE}, opacity ${FALL_ITEM_TRANSITION_DURATION}ms ${DEFAULT_FALL_EASE}`;
export const WORK_TRANSITION = `transform ${WORK_ITEM_TRANSITION_DURATION}ms ${DEFAULT_FALL_EASE}, opacity ${WORK_ITEM_TRANSITION_DURATION}ms ${DEFAULT_FALL_EASE}, filter ${WORK_ITEM_TRANSITION_DURATION}ms ${DEFAULT_FALL_EASE}`;
